#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

from pathlib import Path

from config.pipeline_config import *


# -----------------------------------------------------------------------------
# Instrument constants used by the pipeline (edit if needed)
# -----------------------------------------------------------------------------
GAIN_E_PER_ADU = 2.1      # e-/ADU
READNOISE_E    = 3.8      # e-


# -----------------------------------------------------------------------------
# Active reduction identifiers
# -----------------------------------------------------------------------------
NIGHT_ID = "20260113"
TARGET_NAME = "Dolidze25"
TARGET_FILE_STEM = "dolidze"

RUN_ROOT = Path(
    "/Users/robberto/Library/CloudStorage/Box-Box/My Documents - Massimo Robberto/@Massimo/_Science/2. Projects_HW/2017.SAMOS/_Run8_Science_2026_01"
).resolve()
SAMI_ROOT = RUN_ROOT / "SAMI"
ACQ_REGIONS_DIR = RUN_ROOT / "Regions"


# -----------------------------------------------------------------------------
# High-level roots
# -----------------------------------------------------------------------------
NIGHT_ROOT = SAMI_ROOT / NIGHT_ID
RAW_DIR = NIGHT_ROOT / "raw"
PREPROC_DIR = NIGHT_ROOT / "preprocessed"
REGIONS_DIR = NIGHT_ROOT / "regions"
NIGHT_LOGDIR = NIGHT_ROOT / "logs"

TARGET_ROOT = SAMI_ROOT / TARGET_NAME
INPUT_DIR = TARGET_ROOT / "input"
TABLES_DIR = TARGET_ROOT / "tables"
TARGET_LOGDIR = TARGET_ROOT / "logs"
REDUCED_DIR = TARGET_ROOT / "reduced"

QC_DIR = REDUCED_DIR / "qc"

from config.pipeline_config import REFERENCE_TABLES_DIR
NIST_DIR = REFERENCE_TABLES_DIR / "nist_list"


# -----------------------------------------------------------------------------
# Step directories
# -----------------------------------------------------------------------------
ST00_ORIENT = preproc_step_dir(PREPROC_DIR, "00")
ST01_BIAS = preproc_step_dir(PREPROC_DIR, "01")
ST02_BIASCORR = preproc_step_dir(PREPROC_DIR, "02")
ST03_CRCLEAN = preproc_step_dir(PREPROC_DIR, "03")
ST03P5_ROWSTRIPE = preproc_step_dir(PREPROC_DIR, "03.5")

ST04_TRACES = reduced_step_dir(REDUCED_DIR, "04")
ST05_PIXFLAT = reduced_step_dir(REDUCED_DIR, "05")
ST06_SCIENCE = reduced_step_dir(REDUCED_DIR, "06")
ST07_WAVECAL = reduced_step_dir(REDUCED_DIR, "07")

ST08_EXTRACT1D = reduced_step_dir(REDUCED_DIR, "08")

# Step09 is now implemented as the A/B/A/B OH-clean stage.
# The canonical filesystem location is 09_abab.
ST09_ABAB = REDUCED_DIR / "09_abab"

# Temporary compatibility alias while older scripts still refer to ST09_OH_REFINE.
# New code should use ST09_ABAB.
ST09_OH_REFINE = ST09_ABAB

# Step10 and Step11 keep the standard reduced-step naming.
ST10_TELLURIC = reduced_step_dir(REDUCED_DIR, "10")
ST11_FLUXCAL = reduced_step_dir(REDUCED_DIR, "11")


# QC output tree (generated by QC scripts, separate from pipeline products)
QC04_DIR = qc_step_dir(QC_DIR, "04_traces")
QC05_DIR = qc_step_dir(QC_DIR, "05_pixflat")
QC06_DIR = qc_step_dir(QC_DIR, "06_science")
QC07_DIR = qc_step_dir(QC_DIR, "07_wavecal")
QC08_DIR = qc_step_dir(QC_DIR, "08_extract1d")
QC09_DIR = qc_step_dir(QC_DIR, "09_abab")
QC10_DIR = qc_step_dir(QC_DIR, "10_telluric")
QC11_DIR = qc_step_dir(QC_DIR, "11_fluxcal")


# -----------------------------------------------------------------------------
# Compatibility aliases for existing scripts
# -----------------------------------------------------------------------------
TOP_DIR = SAMI_ROOT
NIGHT_DIR = NIGHT_ROOT
RAW = RAW_DIR
REDUCED = REDUCED_DIR
PROCESSING = TARGET_ROOT
TABLES = TABLES_DIR
WAVECAL = ST07_WAVECAL
INSPECTORS = TARGET_LOGDIR

# legacy drift compatibility
ST04_PIXFLAT = ST04_TRACES
ST05_FLATCORR = ST05_PIXFLAT

# Temporary compatibility for older code that still assumes the historical
# Step09/Step10 naming split. New code should use:
#   ST09_ABAB
#   EXTRACT1D_OHCLEAN
#   ST10_TELLURIC
ST09_TELLURIC = ST10_TELLURIC
ST10_OH_REFINE = ST09_ABAB


WAVECAL_YWIN0 = 1225
WAVECAL_FIRSTLEN = 2875


# -----------------------------------------------------------------------------
# Night / target metadata
# -----------------------------------------------------------------------------
RADEC_EVEN_CSV = REGIONS_DIR / "radec_Even.csv"
RADEC_ODD_CSV = REGIONS_DIR / "radec_Odd.csv"

EVEN_REG_FILE = REGIONS_DIR / "Even_traces_mask_reg.fits"
ODD_REG_FILE = REGIONS_DIR / "Odd_traces_mask_reg.fits"

ARC_1D_WAVELENGTH_ALL = ST07_WAVECAL / NAME_ARC_1D_WAVELENGTH_ALL

STEP11_RADEC = ST11_FLUXCAL / NAME_STEP11_RADEC
STEP11_PHOTCAT = ST11_FLUXCAL / NAME_STEP11_PHOTCAT
STEP11_QAPLOT = ST11_FLUXCAL / NAME_STEP11_QAPLOT
# -----------------------------------------------------------------------------
# Raw and preprocessed input selections for this reduction
# -----------------------------------------------------------------------------
BIAS_FILES = [f"{i:03d}.bias.fits" for i in range(1, 21)]

SCIENCE_FILES = [
    "021.dolidze_biascorr_cr_rowcorr.fits",
    "022.dolidze_biascorr_cr_rowcorr.fits",
    "023.dolidze_biascorr_cr_rowcorr.fits",
    "024.dolidze_biascorr_cr_rowcorr.fits",
    # "025.dolidze_biascorr_cr_rowcorr.fits",
    # "063.dolidze_biascorr_cr_rowcorr.fits",
]

ARC_FILES = [
    "035.arc_biascorr_cr_rowcorr.fits",
    "036.arc_biascorr_cr_rowcorr.fits",
    "037.arc_biascorr_cr_rowcorr.fits",
    "044.arc_biascorr_cr_rowcorr.fits",
    "048.arc_biascorr_cr_rowcorr.fits",
    "049.arc_biascorr_cr_rowcorr.fits",
]

QUARTZ_FILES = [
    "029.quartz_biascorr_cr_rowcorr.fits",
    "030.quartz_biascorr_cr_rowcorr.fits",
    "031.quartz_biascorr_cr_rowcorr.fits",
    "032.quartz_biascorr_cr_rowcorr.fits",
    "033.quartz_biascorr_cr_rowcorr.fits",
    "034.quartz_biascorr_cr_rowcorr.fits",
    "038.quartz_biascorr_cr_rowcorr.fits",
    "039.quartz_biascorr_cr_rowcorr.fits",
    "040.quartz_biascorr_cr_rowcorr.fits",
    "041.quartz_biascorr_cr_rowcorr.fits",
    "042.quartz_biascorr_cr_rowcorr.fits",
    "043.quartz_biascorr_cr_rowcorr.fits",
    "050.quartz_biascorr_cr_rowcorr.fits",
    "051.quartz_biascorr_cr_rowcorr.fits",
    "052.quartz_biascorr_cr_rowcorr.fits",
    "053.quartz_biascorr_cr_rowcorr.fits",
]

MASK_FILES = [
    "054.mask_biascorr_cr_rowcorr.fits",
    "055.mask_biascorr_cr_rowcorr.fits",
    "056.mask_biascorr_cr_rowcorr.fits",
    "057.mask_biascorr_cr_rowcorr.fits",
]

ARC_SLITS_ON = "036.arc_biascorr_cr_rowcorr.fits"
ARC_SLITS_OFF = "037.arc_biascorr_cr_rowcorr.fits"

QUARTZ_SLITS_OFF = "038.quartz_biascorr_cr_rowcorr.fits"
QUARTZ_SLITS_ON_EVEN = "039.quartz_biascorr_cr_rowcorr.fits"
QUARTZ_SLITS_ON_ODD = "040.quartz_biascorr_cr_rowcorr.fits"

# -----------------------------------------------------------------------------
# SISI Image for Astrometry
# -----------------------------------------------------------------------------

SISI_IMAGE_FITS = SISI_DIR / "Coadd_i_median_078-082_ff_flipx_wcs_manual.fits"

# -----------------------------------------------------------------------------
# Canonical products
# -----------------------------------------------------------------------------
# IMPORTANT DESIGN RULE
# ---------------------
# This file is TARGET-SPECIFIC.
#
# Therefore this section should define the FULL PATHS to canonical products for
# this target only, by combining:
#
#   1) #   1) target-specific directories (ST08_EXTRACT1D, ST09_ABAB, ST10_TELLURIC, ...)
#   2) pipeline-generic canonical filenames from config.pipeline_config
#
# The bare filenames themselves are defined centrally in pipeline_config.py.
# That avoids repeating filename conventions across targets such as Dolidze25,
# Dolidze26, etc., while keeping the resolved paths target-specific.
#
# Example:
#   EXTRACT1D_OHCLEAN = ST09_OH_REFINE / NAME_EXTRACT1D_OHCLEAN
#
# Temporary compatibility aliases may remain while older scripts are still being
# migrated, but new code should use the canonical variables defined here.
# -----------------------------------------------------------------------------

# preprocessed / night-level
MASTER_BIAS_FITS = ST01_BIAS / NAME_MASTER_BIAS
BIASCORR_DIR = ST02_BIASCORR
CRCLEAN_DIR = ST03_CRCLEAN

# step 04
EVEN_TRACES_GEOM = ST04_TRACES / NAME_EVEN_TRACES_GEOM
ODD_TRACES_GEOM = ST04_TRACES / NAME_ODD_TRACES_GEOM

EVEN_TRACES_MASK = ST04_TRACES / NAME_EVEN_TRACES_MASK
ODD_TRACES_MASK = ST04_TRACES / NAME_ODD_TRACES_MASK

EVEN_TRACES_SLITID = ST04_TRACES / NAME_EVEN_TRACES_SLITID
ODD_TRACES_SLITID = ST04_TRACES / NAME_ODD_TRACES_SLITID

EVEN_TRACES_TABLE = ST04_TRACES / NAME_EVEN_TRACES_TABLE
ODD_TRACES_TABLE = ST04_TRACES / NAME_ODD_TRACES_TABLE

# step 05
PIXFLAT_EVEN = ST05_PIXFLAT / NAME_PIXFLAT_EVEN
PIXFLAT_ODD = ST05_PIXFLAT / NAME_PIXFLAT_ODD

EVEN_PIXFLAT = PIXFLAT_EVEN
ODD_PIXFLAT = PIXFLAT_ODD

# step 06
FINAL_SCIENCE = ST06_SCIENCE / final_science_name(TARGET_FILE_STEM)

SCI_EVEN_TRACECOORDS = ST06_SCIENCE / science_tracecoords_name(TARGET_FILE_STEM, "EVEN")
SCI_ODD_TRACECOORDS = ST06_SCIENCE / science_tracecoords_name(TARGET_FILE_STEM, "ODD")

# step 07
MASTER_ARC_DIFF = ST07_WAVECAL / NAME_MASTER_ARC_DIFF
MASTER_ARC_FITS = ST07_WAVECAL / NAME_MASTER_ARC
WAVESOL_FITS = ST07_WAVECAL / NAME_WAVESOL
WAVESOL_ALL_FITS = ST07_WAVECAL / NAME_WAVESOL_ALL
SHIFT2M_TABLE = ST07_WAVECAL / NAME_SHIFT2M_TABLE

ARC_FITS = MASTER_ARC_DIFF
WAVESOL_ALL = WAVESOL_ALL_FITS
ARC_1D_WAVELENGTH_ALL = ST07_WAVECAL / NAME_ARC_1D_WAVELENGTH_ALL

# step 08
EXTRACT1D_EVEN = ST08_EXTRACT1D / NAME_EXTRACT1D_EVEN
EXTRACT1D_ODD = ST08_EXTRACT1D / NAME_EXTRACT1D_ODD
EXTRACT1D_ALL = ST08_EXTRACT1D / NAME_EXTRACT1D_ALL
EXTRACT1D_WAV = ST08_EXTRACT1D / NAME_EXTRACT1D_WAV

# step 09 = ABAB OH clean
# The historical OH-shift CSV products are kept only for backward compatibility
# with older scripts. The canonical science product is EXTRACT1D_OHCLEAN.
OH_SHIFT_CSV = ST09_ABAB / NAME_OH_SHIFT_CSV
OH_SHIFT_QC_CSV = ST09_ABAB / NAME_OH_SHIFT_QC_CSV

# Canonical merged Step09 science product.
# This is the file that Step10 should consume.
EXTRACT1D_OHCLEAN = ST09_ABAB / NAME_EXTRACT1D_OHCLEAN

# Temporary compatibility alias for scripts that still expect the old variable
# name EXTRACT1D_OHREF. New code should use EXTRACT1D_OHCLEAN.
EXTRACT1D_OHREF = EXTRACT1D_OHCLEAN

# step 10 = telluric
TELLURIC_TEMPLATE = ST10_TELLURIC / NAME_TELLURIC_TEMPLATE
EXTRACT1D_TELLCOR = ST10_TELLURIC / NAME_EXTRACT1D_TELLCOR

# step 11 = flux calibration
STEP11_INPUT_SPECTRA = EXTRACT1D_TELLCOR
STEP11_RADEC = ST11_FLUXCAL / NAME_STEP11_RADEC
STEP11_PHOTCAT = ST11_FLUXCAL / NAME_STEP11_PHOTCAT
STEP11_QAPLOT = ST11_FLUXCAL / NAME_STEP11_QAPLOT
EXTRACT1D_FLUXCAL = ST11_FLUXCAL / NAME_EXTRACT1D_FLUXCAL
FLUXCAL_SUMMARY_CSV = ST11_FLUXCAL / NAME_FLUXCAL_SUMMARY_CSV


# -----------------------------------------------------------------------------
# Temporary compatibility aliases
# -----------------------------------------------------------------------------
# These aliases exist only to support scripts that still use historical naming
# from the old Step09/Step10 ordering. New code should NOT use them.
# -----------------------------------------------------------------------------
LEGACY_OH_SHIFT_CSV = OH_SHIFT_QC_CSV
LEGACY_EXTRACT1D_TELLCOR = EXTRACT1D_TELLCOR
LEGACY_EXTRACT1D_OHREF = EXTRACT1D_OHREF

REGIONS = REGIONS_DIR

# Historical stage-name compatibility only.
ST10_OH = ST09_OH_REFINE
ST09_TELL = ST10_TELLURIC
ST09_TELLURIC = ST10_TELLURIC
ST10_OH_REFINE = ST09_OH_REFINE

# -----------------------------------------------------------------------------
# Input bookkeeping
# -----------------------------------------------------------------------------
TARGET_MANIFEST_YAML = INPUT_DIR / "reduction_manifest.yaml"
TARGET_MANIFEST_JSON = INPUT_DIR / "reduction_manifest.json"
TARGET_NIGHTS_USED = INPUT_DIR / "nights_used.txt"
TARGET_FILES_SCIENCE = INPUT_DIR / "files_science.txt"
TARGET_FILES_ARC = INPUT_DIR / "files_arc.txt"
TARGET_FILES_QUARTZ = INPUT_DIR / "files_quartz.txt"


# -----------------------------------------------------------------------------
# Directory collection
# -----------------------------------------------------------------------------
ALL_DIRS = [
    RAW_DIR,
    PREPROC_DIR,
    REGIONS_DIR,
    NIGHT_LOGDIR,
    INPUT_DIR,
    REDUCED_DIR,
    TABLES_DIR,
    TARGET_LOGDIR,
    ST00_ORIENT,
    ST01_BIAS,
    ST02_BIASCORR,
    ST03_CRCLEAN,
    ST03P5_ROWSTRIPE,
    ST04_TRACES,
    ST05_PIXFLAT,
    ST06_SCIENCE,
    ST07_WAVECAL,
    ST08_EXTRACT1D,
    ST09_ABAB,
    ST10_TELLURIC,
    ST11_FLUXCAL,
    QC_DIR,
    QC04_DIR,
    QC05_DIR,
    QC06_DIR,
    QC07_DIR,
    QC08_DIR,
    QC09_DIR,
    QC10_DIR,
    QC11_DIR,
]


# -----------------------------------------------------------------------------
# Helpers expected by step scripts
# -----------------------------------------------------------------------------
def ensure_directories() -> None:
    from config.pipeline_config import ensure_directories as _ensure
    _ensure(ALL_DIRS)


def summary() -> dict[str, str]:
    return {
        "REPO_ROOT": str(REPO_ROOT),
        "SAMI_ROOT": str(SAMI_ROOT),
        "NIGHT_ROOT": str(NIGHT_ROOT),
        "TARGET_ROOT": str(TARGET_ROOT),
        "RAW_DIR": str(RAW_DIR),
        "PREPROC_DIR": str(PREPROC_DIR),
        "REGIONS_DIR": str(REGIONS_DIR),
        "REDUCED_DIR": str(REDUCED_DIR),
        "TABLES_DIR": str(TABLES_DIR),
        "QC_DIR": str(QC_DIR),
        "ST07_WAVECAL": str(ST07_WAVECAL),
        "ST08_EXTRACT1D": str(ST08_EXTRACT1D),
        "ST09_ABAB": str(ST09_ABAB),
        "ST09_OH_REFINE": str(ST09_OH_REFINE),  # compatibility alias
        "ST10_TELLURIC": str(ST10_TELLURIC),
        "ST11_FLUXCAL": str(ST11_FLUXCAL),
        "STEP11_INPUT_SPECTRA": str(STEP11_INPUT_SPECTRA),
    }
